category: APMAPPLICATION
lookups:
  - entityTypes:
      - domain: APM
        type: APPLICATION
    tags:
      matchingMode: ALL
      predicates:
        - tagKeys: ["faas.app_name", "cloud.resource_id"]
          field: resourceId 
    onMatch:
      onMultipleMatches: RELATE_ALL
    onMiss:
      action: NO_OP 