category: DATABASE
lookups:
  - entityTypes:
    - domain: INFRA
      type: AWSRDSDBCLUSTER
    - domain: INFRA
      type: AWSRDSDBINSTANCE
    - domain: INFRA
      type: AZURESQLDATABASE
    - domain: INFRA
      type: AZURESQLSERVER
    - domain: INFRA
      type: AZUREPOSTGRESQLFLEXIBLESERVER
    - domain: INFRA
      type: AZURESQLELASTICPOOL
    - domain: INFRA
      type: AZUREPOSTGRESQLSERVER
    - domain: INFRA
      type: AZURESQLMANAGEDINSTANCE
    - domain: INFRA
      type: AZUREMYSQLFLEXIBLESERVER
    - domain: INFRA
      type: AZUREMYSQLSERVER
    - domain: INFRA
      type: AZUREMARIADBSERVER
    - domain: INFRA
      type: GCPCLOUDSQL
    - domain: INFRA
      type: GCPALLOYDBDATABASE
    - domain: INFRA
      type: GCPALLOYDBINSTANCE
    - domain: INFRA
      type: GCPALLOYDBCLUSTER
    - domain: INFRA
      type: MSSQLINSTANCE
    - domain: INFRA
      type: MYSQLNODE
    - domain: INFRA
      type: POSTGRESQLINSTANCE
    - domain: INFRA
      type: ORACLEDBINSTANCE
    tags:
      matchingMode: ANY
      predicates:
        - tagKeys: ["endpoint", "nr.endpoint", "aws.endpoint", "aws.readerEndpoint", "aws.customEndpoints", "aws.rds.endpoint", "aws.rds.readerEndpoint", "aws.rds.customEndpoints"]
          field: endpoint
    onMatch:
     onMultipleMatches: RELATE_ALL
    onMiss:
      action: CREATE_UNINSTRUMENTED
      uninstrumented:
        type: DATABASE