category: DATABASE
lookups:
  - entityTypes:
    - INFRA-AWSRDSDBCLUSTER
    - INFRA-AWSRDSDBINSTANCE
    - INFRA-AZURESQLSERVER
    - INFRA-AZUREPOSTGRESQLFLEXIBLESERVER
    - INFRA-AZURESQLELASTICPOOL
    - INFRA-AZUREPOSTGRESQLSERVER
    - INFRA-AZURESQLMANAGEDINSTANCE
    - INFRA-AZUREMYSQLFLEXIBLESERVER
    - INFRA-AZUREMYSQLSERVER
    - INFRA-AZUREMARIADBSERVER
    - INFRA-GCPCLOUDSQL
    - INFRA-GCPALLOYDBDATABASE
    - INFRA-GCPALLOYDBINSTANCE
    - INFRA-GCPALLOYDBCLUSTER
    - INFRA-MSSQLINSTANCE
    - INFRA-MYSQLNODE
    - INFRA-POSTGRESQLINSTANCE
    - INFRA-ORACLEDBINSTANCE
    - INFRA-AWSRDSPROXY
    - INFRA-AWSREDSHIFTCLUSTER
    attributes:
      matchingMode: ANY
      predicates:
        - attributeKeys: ["tags.endpoint", "tags.nr.endpoint", "tags.aws.endpoint", "tags.aws.readerEndpoint", "tags.aws.customEndpoints", "tags.aws.rds.endpoint", "tags.aws.rds.readerEndpoint", "tags.aws.rds.customEndpoints", "tags.aws.rds.proxyEndpoint", "tags.aws.redshift.serverAddress", "tags.azure.endpoint", "tags.azure.failoverGroupDomainName", "tags.gcp.privateIpAddress", "tags.gcp.publicIpAddress", "tags.gcp.connectionName"]
          field: endpoint
    onMatch:
     onMultipleMatches: RELATE_ALL
    onMiss:
      action: CREATE_UNINSTRUMENTED
      uninstrumented:
        type: DATABASE
