category: KUBERNETES_DEPLOYMENT
lookups:
  - entityTypes:
    - domain: INFRA
      type: KUBERNETES_DEPLOYMENT
    tags:
      matchingMode: ALL
      predicates:
        - tagKeys: ["k8s.deploymentName"]
          field: k8s.deployment.name
        - tagKeys: ["k8s.namespaceName"]
          field: k8s.namespace.name
        - tagKeys: ["k8s.clusterName"]
          field: k8s.cluster.name
    onMatch:
      onMultipleMatches: RELATE_ALL
    onMiss:
      action: NO_OP