category: KUBERNETES_DEPLOYMENT
lookups:
  - entityTypes:
    - domain: INFRA
      type: KUBERNETES_DEPLOYMENT
    tags:
      matchingMode: ANY
      predicates:
        - tagKeys: ["k8s.replicasetName"]
          field: replicaset
        - tagKeys: ["k8s.namespaceName"]
          field: namespace
        - tagKeys: ["k8s.clusterName"]
          field: cluster
    onMatch:
      onMultipleMatches: RELATE_ALL
    onMiss:
      action: NO_OP