category: VIDEOAPPLICATION
lookups:
  - entityTypes:
      - domain: MOBILE
        type: APPLICATION
      - domain: BROWSER
        type: APPLICATION
    tags:
      matchingMode: ANY 
      predicates:
        - tagKeys: ["appName"]
          field: appName
    onMatch:
      onMultipleMatches: RELATE_ALL
    onMiss:
      action: NO_OP