errors:
  title: Errors
  unit: COUNT
  query:
    select: count(*)
    from: JavaScriptError
    eventId: entity.guid
    eventName: entity.name
throughputAjax:
  title: Ajax throughput (rpm)
  unit: REQUESTS_PER_MINUTE
  query:
    select: rate(count(*), 1 minute)
    from: AjaxRequest
    eventId: entity.guid
    eventName: entity.name
views:
  title: Views
  unit: COUNT
  query:
    select: count(*)
    from: MicroFrontEndTiming
    eventId: entity.guid
    eventName: entity.name
loadTime:
  title: Load Time (ms)
  unit: MS
  query:
    select: average(timeToLoad)
    from: MicroFrontEndTiming
    eventId: entity.guid
    eventName: entity.name
