views:
  title: Views
  unit: COUNT
  query:
    select: count(*)
    from: MicroFrontendView
errors:
  title: Errors
  unit: COUNT
  query:
    select: count(*)
    from: MicroFrontendJavaScriptError
loadSeconds:
  title: Load time (s)
  unit: SECONDS
  query:
    select: average(duration)
    from: MicroFrontendLoadTiming