errors:
  title: Errors
  unit: COUNT
  goldenMetric: errors
throughputAjax:
  title: Ajax throughput (rpm)
  unit: REQUESTS_PER_MINUTE
  goldenMetric: throughputAjax
views:
  title: Views
  unit: COUNT
  goldenMetric: views
loadTime:
  title: Load Time
  unit: SECONDS
  goldenMetric: loadTime
