ruleGroupIterationsMissed:
  title: Rule Group Iterations Missed
  unit: COUNT
  queries:
    aws:
      select: latest(aws.prometheus.RuleGroupIterationsMissed)
      from: Metric
      eventId: entity.guid
      eventName: entity.name
ruleEvaluations:
  title: Rule Evaluations
  unit: COUNT
  queries:
    aws:
      select: latest(aws.prometheus.RuleEvaluations)
      from: Metric
      eventId: entity.guid
      eventName: entity.name
ruleEvaluationFailures:
  title: Rule Evaluation Failures
  unit: COUNT
  queries:
    aws:
      select: latest(aws.prometheus.RuleEvaluationFailures)
      from: Metric
      eventId: entity.guid
      eventName: entity.name
