driverMemory:
  title: Average Driver Memory Used
  query:
    select: average(spark.app.executor.memoryUsed)
    from: Metric
    eventId: entity.guid

jobs:
  title: Spark Jobs
  query:
    select: latest(spark.app.jobs)
    from: Metric
    facet: sparkAppJobStatus
    eventId: entity.guid



