domain: EXT
type: PROMETHEUS_SERVER
synthesis:
  rules:
    - identifier: host.hostname
      name: host.hostname
      encodeIdentifierInGUID: true
      conditions:
        - attribute: metricName
          value: "node_uname_info"
configuration:
  entityExpirationTime: EIGHT_DAYS
  alertable: true
