clusterName:
  title: Cluster name
  unit: STRING
  tag:
    key: k8s.clusterName
namespaceName:
  title: Namespace name
  unit: STRING
  tag:
    key: k8s.namespaceName
failedSamples:
  goldenMetric: failedSamples
  title: Failed samples
  unit: REQUESTS_PER_SECOND
