relationships:
  - name: apmServiceCallsInfraKinesisStream
    version: "1"
    origins:
      - Distributed Tracing
    conditions:
      - attribute: eventType
        anyOf: [ "Span" ]
      - attribute: cloud.platform
        anyOf: [ "aws_kinesis_data_streams"]
      - attribute: cloud.resource_id
        regex: "^arn:aws:kinesis:([^:]*):([^:]*):stream/([^:]*)"
    relationship:
      expires: P75M
      relationshipType: CALLS
      source:
        extractGuid:
          attribute: entity.guid
      target:
        lookupGuid:
          candidateCategory: AWSKINESISSTREAM
          fields:
            - field: cloudResourceId
              attribute: cloud.resource_id
