relationships:
  - name: apmCallsGenericDatabaseViaRoute53
    version: "1"
    origins:
      - APM Metrics
    conditions:
      # Datastore/instance/JDBC/db.example.com/3306
      - attribute: metricName
        regex: "^datastore/instance/(?:mysql|postgres|mssql|oracle|mariadb|jdbc)/[^/;]*/.*"
    relationship:
      expires: P75M
      relationshipType: CALLS
      source:
        extractGuid:
          attribute: entity.guid
      target:
        lookupGuid:
          candidateCategory: AWSROUTE53RECORDSET
          fields:
            - field: recordSetUrl
              attribute: metricName__4
