relationships:
  - name: apmApplicationProducesToAzureServiceBusNamespace
    version: "1"
    entitlements:
      matching: anyOf
      values:
        - advanced_maps_ccu
        - advanced_maps_discount_usage
        - auto_discovery_entities_ccu
        - auto_discovery_entities_ccu_discount_usage
    origins:
      - Distributed Tracing 
    conditions:
      - attribute: eventType
        anyOf: [ "Span" ]
      - attribute: server.address
        regex: '^[a-z0-9\-]+\.servicebus\.windows\.net$'
      - attribute: span.kind
        anyOf: [ "producer" ] 
      - attribute: name 
        regex: "MessageBroker/[^/]*/[^/]*/Produce/Named/[^/]*"
      - attribute: messaging.destination.name 
        present: true
    relationship:
      expires: P75M
      relationshipType: PRODUCES
      source:
        extractGuid:
          attribute: entity.guid
      target:
        lookupGuid:
          candidateCategory: AZURESERVICEBUSNAMESPACE 
          fields:
            - field: endpoint 
              attribute: server.address

  - name: apmApplicationConsumesFromAzureServiceBusNamespace
    version: "1"
    entitlements:
      matching: anyOf
      values:
        - advanced_maps_ccu
        - advanced_maps_discount_usage
        - auto_discovery_entities_ccu
        - auto_discovery_entities_ccu_discount_usage
    origins:
      - Distributed Tracing
    conditions:
      - attribute: eventType
        anyOf: [ "Span" ]
      - attribute: server.address
        regex: '^[a-z0-9\-]+\.servicebus\.windows\.net$'
      - attribute: span.kind
        anyOf: [ "consumer" ] 
      - attribute: name 
        regex: "MessageBroker/[^/]*/[^/]*/Consume/Named/[^/]*"
      - attribute: messaging.destination.name 
        present: true
    relationship:
      expires: P75M
      relationshipType: CONSUMES 
      source:
        extractGuid:
          attribute: entity.guid
      target:
        lookupGuid:
          candidateCategory: AZURESERVICEBUSNAMESPACE 
          fields:
            - field: endpoint
              attribute: server.address