relationships:
  - name: apmApplicationCallsInfraRedisInstance
    version: "1"
    origins:
      - APM Metrics
    conditions:
      - attribute: metricName
        # "datastore/instance/redis/$host/$port"
        startsWith: "datastore/instance/redis/"
    relationship:
      expires: P75M
      relationshipType: CALLS
      source:
        extractGuid:
          attribute: entity.guid
      target:
        buildGuid:
          account:
            lookup: yes
          domain:
            value: INFRA
          type:
            value: REDISINSTANCE
            valueInGuid: NA
          identifier:
            fragments:
              - value: "instance:"
              - attribute: metricName__4 # hostname
              - value: ":"
              - attribute: metricName__5 # port
            hashAlgorithm: FARM_HASH
