relationships:
  - name: apmCallsInfraAppSyncApi
    version: "1"
    origins:
      - Distributed Tracing
    conditions:
      - attribute: eventType
        anyOf: [ "Span" ]
      - attribute: Peer.Hostname
        regex: "[a-z0-9]{25}\.appsync-api\.us-east-2\.amazonaws\.com"
    relationship:
      expires: P75M
      relationshipType: CALLS
      source:
        extractGuid:
          attribute: entity.guid
      target:
        lookupGuid:
          candidateCategory: AWSAPPSYNCAPI
          fields:
            - field: httpUrl
              attribute: Http.Url