relationships:
  - name: apmCallsLambdafunction
    version: "1"
    origins:
      - Distributed Tracing
    conditions:
      - attribute: eventType
        anyOf: [ "Span" ]
      - attribute: cloud.platform
        anyOf: [ "aws_lambda"]
      - attribute: cloud.resource_id
        regex: "^arn:aws:lambda:([^:]*):([0-9]*):function:([^:]*)$"
    relationship:
      expires: P75M
      relationshipType: CALLS
      source:
        extractGuid:
          attribute: entity.guid
      target:
        lookupGuid:
          candidateCategory: AWSLAMBDAFUNCTION
          fields:
            - field: awsLambdaArn
              attribute: cloud.resource_id

  - name: awsLambdaFunctionIsAPM
    version: "1"
    origins:
      - Distributed Tracing
    conditions:
      - attribute: eventType
        anyOf: [ "Span" ]
      - attribute: aws.lambda.arn
        regex: "^arn:aws:lambda:([^:]*):([0-9]*):function:([^:]*)$"
    relationship:
      expires: P75M
      relationshipType: IS
      source:
        extractGuid:
          attribute: entity.guid
      target:
        lookupGuid:
          candidateCategory: AWSLAMBDAFUNCTION
          fields:
            - field: awsLambdaArn
              attribute: aws.lambda.arn