relationships:
  - name: apmCallsLambdafunction
    version: "1"
    entitlements:
      matching: anyOf
      values:
        - advanced_maps_ccu
        - advanced_maps_discount_usage
        - auto_discovery_entities_ccu
        - auto_discovery_entities_ccu_discount_usage
    origins:
      - Distributed Tracing
    conditions:
      - attribute: eventType
        anyOf: [ "Span" ]
      - attribute: cloud.platform
        anyOf: [ "aws_lambda"]
      - attribute: cloud.resource_id
        regex: "^arn:aws:lambda:([^:]*):([0-9]*):function:([^:]*)$"
    relationship:
      expires: P75M
      relationshipType: CALLS
      source:
        extractGuid:
          attribute: entity.guid
      target:
        lookupGuid:
          candidateCategory: AWSLAMBDAFUNCTION
          fields:
            - field: awsLambdaArn
              attribute: cloud.resource_id

  - name: awsLambdaFunctionHOSTSApm
    version: "1"
    entitlements:
      matching: anyOf
      values:
        - advanced_maps_ccu
        - advanced_maps_discount_usage
        - auto_discovery_entities_ccu
        - auto_discovery_entities_ccu_discount_usage
    origins:
      - Distributed Tracing
    conditions:
      - attribute: eventType
        anyOf: [ "Span" ]
      - attribute: aws.lambda.arn
        regex: "^arn:aws:lambda:([^:]*):([0-9]*):function:([^:]*)$"
    relationship:
      expires: P75M
      relationshipType: HOSTS
      source:
        lookupGuid:
          candidateCategory: AWSLAMBDAFUNCTION
          fields:
            - field: awsLambdaArn
              attribute: aws.lambda.arn
      target:
        extractGuid:
          attribute: entity.guid
