relationships:
  - name: extApplicationCallsInfraDynamoDBTable
    version: "1"
    origins:
      - OpenTelemetry
    conditions:
      - attribute: eventType
        anyOf: [ "Span" ]
      - attribute: rpc.service
        anyOf: [ "DynamoDB" ]
    relationship:
      expires: P75M
      relationshipType: CALLS
      source:
        extractGuid:
          attribute: entity.guid
      target:
        lookupGuid:
          candidateCategory: AWSDYNAMODBTABLE
          fields:
            - field: awsAccountId
              attribute: cloud.account.id
            - field: awsRegion
              attribute: cloud.region
            - field: awsTableName
              attribute: aws.tableName