relationships:
  - name: mediaStreamingCallsMobileApplication
    version: "1"
    origins:
      - APM Metrics
    conditions:
      - attribute: eventType
        anyOf: ["VideoAction"]
      - attribute: src
        anyOf: ["Android", "IOS"]
    relationship:
      expires: P75M
      relationshipType: CALLS
      source:
        buildGuid:
          account:
            lookup: true
          domain:
            value: MOBILE
          type:
            value: APPLICATION
          identifier:
            fragments:
              - attribute: appId
      target:
        extractGuid:
          attribute: entity.guid