relationships:
  - name: mobileApplicationContainsVideoAction
    version: "1"
    origins:
      - APM Metrics
    conditions:
      - attribute: eventType
        startsWith: "Video"
        caseSensitive: true
      - attribute: src
        anyOf: ["Android", "IOS"]
    relationship:
      expires: P75M
      relationshipType: CONTAINS
      source:
        extractGuid:
          attribute: entity.guid
      target:
        lookupGuid:
          candidateCategory: VIDEO
          fields:
            - field: appName
              capture:
                attribute: appName
                regex: ".*-mediaplayer$"