alertManagerAlertsReceived:
  title: Alert Manager Alerts Received
  unit: COUNT
  queries:
    aws:
      select: latest(aws.prometheus.AlertManagerAlertsReceived)
      from: Metric
      eventId: entity.guid
      eventName: entity.name
alertManagerNotificationsFailed:
  title: Alert Manager Notifications Failed
  unit: COUNT
  queries:
    aws:
      select: latest(aws.prometheus.AlertManagerNotificationsFailed)
      from: Metric
      eventId: entity.guid
      eventName: entity.name
discardedSamples:
  title: Discarded Samples
  unit: COUNT
  queries:
    aws:
      select: latest(aws.prometheus.DiscardedSamples)
      from: Metric
      eventId: entity.guid
      eventName: entity.name
