providerAccountName:
  title: AWS account
  unit: STRING
  tag:
    key: providerAccountName
region:
  title: Region
  unit: STRING
  tag:
    key: aws.awsRegion
alertManagerAlertsReceived:
  goldenMetric: alertManagerAlertsReceived
  title: Alert Manager Alerts Received
  unit: COUNT
alertManagerNotificationsFailed:
  goldenMetric: alertManagerNotificationsFailed
  title: Alert Manager Notifications Failed
  unit: COUNT
discardedSamples:
  goldenMetric: discardedSamples
  title: Discarded Samples
  unit: COUNT
