ingressBytes:
  title: Ingress bytes
  unit: BYTES
  queries:
    azure: 
      select: sum(azure.media.mediaservices.videoanalyzers.IngressBytes)
      from: Metric
      eventId: entity.guid
      eventName: entity.name
pipelines:
  title: Pipelines
  unit: COUNT
  queries:
    azure:
      select: sum(azure.media.mediaservices.videoanalyzers.Pipelines)
      from: Metric
      eventId: entity.guid
      eventName: entity.name